#!/bin/bash

# --------------------------------------------------------------------------------------------
# Driver: hotstart
# Operation: clearinstance
#
# Stops and clears one hotstart instance by calling 'stopinstance --clear'.
#
# This must take as an argument either a '--label <LABEL-NAME>' or '--port <P2P-PORT-NUMBER>'
#   argument to identify the instance to stop and clear. That argument will be forwarded to
#   hotstart/stopinstance.
#
# See: hotstart/stopinstance
# --------------------------------------------------------------------------------------------

# first, be at this script's directory
cd "$(dirname "$0")"

# Append the --clear argument to the command-line arguments
args=("$@" "--clear")

# Execute the 'stop' script with the modified arguments
./stopinstance "${args[@]}"
