#!/bin/bash

# --------------------------------------------------------------------------------------------
# Driver: hotstart
# Operation: clear
#
# Stops and clears all hotstart instances by calling 'stopinstance --all --clear'.
#
# See: hotstart/stopinstance
# --------------------------------------------------------------------------------------------

# first, be at this script's directory
cd "$(dirname "$0")"

# Append the --all --clear arguments to the command-line arguments
args=("$@" "--all" "--clear")

# Execute the 'stop' script with the modified arguments
./stopinstance "${args[@]}"
