#!/bin/bash

# --------------------------------------------------------------------------------------------
# Driver: hotstart
# Operation: stop
#
# Stops all hotstart instances by calling 'stopinstance --all'.
#
# See: hotstart/stopinstance
# --------------------------------------------------------------------------------------------

# first, be at this script's directory
cd "$(dirname "$0")"

# Append the --all argument to the command-line arguments
args=("$@" "--all")

# Execute the 'stop' script with the modified arguments
./stopinstance "${args[@]}"
