#!/bin/bash

# --------------------------------------------------------------------------------------------
# Driver: coldstart
# Operation: clear
#
# This operation ensures the coldstart nodeos instance is stopped (by calling coldstart/stop)
#   and then clears the cth/local/coldstart/ directory.
#
# If coldstart/start is called again after this, it will start over the state from scratch.
# --------------------------------------------------------------------------------------------

# go to driver's dir to call stop
cd "$(dirname "$0")"

# stop the node if it isn't already stopped
./stop

# now make sure the current working dir is the driver's working dir
# at ../../local/coldstart/
if ! cd "../../local/coldstart"; then
  echo "coldstart clear: cannot change directory to local/coldstart; assuming no running coldstart nodeos to clear"
  exit 0
fi

# clear node data -- after this, coldstart/start will start over from scratch

rm -rf ./data
rm -rf ./protocol_features
rm -f chain.log
rm -f config.ini
rm -f genesis.json
rm -f start_nodeos.sh
